apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: project-1
spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: 218550331294.dkr.ecr.us-east-1.amazonaws.com/shopping-site-frontend:8fe0b8629f432357371870836af34934533f45a7

          ports:
            - containerPort: 8501

          env:
            - name: API_URL
              value: "http://backend-service:8084"


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: project-1
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501