apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: project-1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: 218550331294.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:8fe0b8629f432357371870836af34934533f45a7

          ports:
            - containerPort: 8084

          env:
            - name: SERVER_PORT
              value: "8084"

            - name: MYSQL_HOST
              value: "shopping-mysql.ccdkeeisasr8.us-east-1.rds.amazonaws.com"

            - name: MYSQL_USERNAME
              value: "admin"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

---

apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: project-1

spec:
  selector:
    app: backend

  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084

  type: ClusterIP